name: main-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shell:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Install Tools'
      run: |
        sudo apt-get install expect
    - name: 'Run'
      run: |
        expect ./my-script.exp

  node:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v1
    - name: 'Install Tools'
      run: |
        sudo apt-get install expect
    - name: 'Run'
      run: |
        expect ./app.exp
